//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551d)
//
// On Thu Jul  4 08:48:21 EDT 2024
//
//
// Ports:
// Name                         I/O  size props
// isMMIO                         O     1
// isMMIO_addr                    I    32
//
// Combinational paths from inputs to outputs:
//   isMMIO_addr -> isMMIO
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_isMMIO(isMMIO_addr,
		     isMMIO);
  // value method isMMIO
  input  [31 : 0] isMMIO_addr;
  output isMMIO;

  // signals for module outputs
  wire isMMIO;

  // value method isMMIO
  assign isMMIO =
	     isMMIO_addr == 32'h0000FFF0 || isMMIO_addr == 32'h0000FFF4 ||
	     isMMIO_addr == 32'h0000FFF8 ;
endmodule  // module_isMMIO

